layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects: "matplotlib-cheatsheet"

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: https://www.linkedin.com/in/joy-bhalla-02b787149/
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: https://twitter.com/bhalla_joy
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: python
    web_url: https://github.com/python/cpython
    image_url: https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg

  - name: Financial Markets
    web_url: https://github.com/alpacahq/alpaca-trade-api-python
    image_url: https://pbs.twimg.com/profile_images/954497766843064321/8dml2ago_400x400.jpg

  - name: Machine Learning
    web_url: https://github.com/scikit-learn/scikit-learn
    image_url: https://upload.wikimedia.org/wikipedia/commons/0/05/Scikit_learn_logo_small.svg